# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
Uniform__new <- function(min, max) {
    .Call('RcppSerialization_Uniform__new', PACKAGE = 'RcppSerialization', min, max)
}

#'@export
Uniform__draw <- function(xp, n) {
    .Call('RcppSerialization_Uniform__draw', PACKAGE = 'RcppSerialization', xp, n)
}

#'@export
Uniform__save <- function(xp, is_binary = TRUE, is_gzip = TRUE) {
    .Call('RcppSerialization_Uniform__save', PACKAGE = 'RcppSerialization', xp, is_binary, is_gzip)
}

#'@export
Uniform__load <- function(src, is_binary = TRUE, is_gzip = TRUE) {
    .Call('RcppSerialization_Uniform__load', PACKAGE = 'RcppSerialization', src, is_binary, is_gzip)
}

